language: crystal
crystal:
  - latest
services:
  - docker
before_deploy:
  - mkdir bin
  - echo -e 'require "llvm/lib_llvm"\nrequire "llvm/enums"\n' >> src/cli.cr
  - docker run --rm -it -v $PWD:/freeport -w /freeport jrei/crystal-alpine crystal build src/cli.cr --static --release --no-debug --stats --progress -o bin/freeport
  - strip -s bin/freeport
  - tar -zcvf freeport-$TRAVIS_TAG-linux-x86_64.tar.gz bin/freeport
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: freeport-$TRAVIS_TAG-linux-x86_64.tar.gz
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: never
    on_failure: always
